l= float(input('Digite a largura em metros: '))
a=float(input('Digite a altura em metros '))
mq= (a*l)
tin= (mq/2)
print('O espaço tem o total de {:.2f} metros quadrados\nTinta necessária {:.2f} litros'.format(mq,tin))
