nome= str(input('Digite seu nome completo: ')).strip()
print(nome)
print('Seu nome em maiusculas {}'.format(nome.upper()))
print('Seu nome em minusculas {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras '.format(len(nome)-nome.count(' ')))
#print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa= nome.split()
print('Seu primeiro nome tem {} letras'.format(len(separa[0])))
